/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/ctP6kOHV8eF
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { TableHead, TableRow, TableHeader, TableCell, TableBody, Table } from "@/components/ui/table"

const Menu = () => {
  return (
    <>
      <section className="w-full py-8 md:py-12 lg:py-16 xl:py-20">
        <div className="container px-4 md:px-6">
          <div className="flex flex-col items-center space-y-4 text-center">
            <div className="space-y-2">
              <h1 className="text-2xl font-bold tracking-tighter sm:text-3xl md:text-4xl lg:text-5xl/none">
                Table Tennis Practice
              </h1>
              <p className="mx-auto max-w-[600px] text-gray-500 md:text-base dark:text-gray-400">
                Sign up for our table tennis practice sessions and improve your skills.
              </p>
            </div>
          </div>
        </div>
      </section>
      <section className="w-full py-8 md:py-12 lg:py-16">
        <div className="container px-4 md:px-6">
          <div className="mx-auto max-w-[390px] sm:max-w-[844px]">
            <div className="grid gap-4">
              <div className="bg-white rounded-lg shadow-sm dark:bg-gray-950">
                <div className="p-4 md:p-6">
                  <div className="flex items-center justify-between">
                    <h3 className="text-base font-semibold">Practice Menu</h3>
                    <div className="flex items-center gap-2">
                      <Button size="sm">Filter</Button>
                      <Button size="sm" variant="primary">
                        Register
                      </Button>
                      <Button size="sm">Sort</Button>
                    </div>
                  </div>
                </div>
                <Table>
                  <TableHeader>
                    <TableRow>
                      <TableHead>Description</TableHead>
                      <TableHead>Tags</TableHead>
                      <TableHead>Actions</TableHead>
                    </TableRow>
                  </TableHeader>
                  <TableBody>
                    <TableRow>
                      <TableCell>One-on-one table tennis practice to improve your individual skills.</TableCell>
                      <TableCell>
                        <div className="flex flex-wrap gap-2">
                          <div className="inline-block px-2 py-1 rounded-full bg-gray-100 text-gray-600 dark:bg-gray-800 dark:text-gray-400 text-xs font-medium">
                            Footwork
                          </div>
                          <div className="inline-block px-2 py-1 rounded-full bg-gray-100 text-gray-600 dark:bg-gray-800 dark:text-gray-400 text-xs font-medium">
                            Technique
                          </div>
                        </div>
                      </TableCell>
                      <TableCell>
                        <div className="flex items-center gap-2">
                          <Button size="sm" variant="outline">
                            <DeleteIcon className="w-4 h-4" />
                            Edit
                          </Button>
                          <Button size="sm" variant="destructive">
                            <TrashIcon className="w-4 h-4" />
                            Delete
                          </Button>
                        </div>
                      </TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell>Partner up and practice your doubles strategy and coordination.</TableCell>
                      <TableCell>
                        <div className="flex flex-wrap gap-2">
                          <div className="inline-block px-2 py-1 rounded-full bg-gray-100 text-gray-600 dark:bg-gray-800 dark:text-gray-400 text-xs font-medium">
                            Strategy
                          </div>
                          <div className="inline-block px-2 py-1 rounded-full bg-gray-100 text-gray-600 dark:bg-gray-800 dark:text-gray-400 text-xs font-medium">
                            Coordination
                          </div>
                        </div>
                      </TableCell>
                      <TableCell>
                        <div className="flex items-center gap-2">
                          <Button size="sm" variant="outline">
                            <DeleteIcon className="w-4 h-4" />
                            Edit
                          </Button>
                          <Button size="sm" variant="destructive">
                            <TrashIcon className="w-4 h-4" />
                            Delete
                          </Button>
                        </div>
                      </TableCell>
                    </TableRow>
                    <TableRow>
                      <TableCell>Join a group session and get feedback from our experienced coaches.</TableCell>
                      <TableCell>
                        <div className="flex flex-wrap gap-2">
                          <div className="inline-block px-2 py-1 rounded-full bg-gray-100 text-gray-600 dark:bg-gray-800 dark:text-gray-400 text-xs font-medium">
                            Feedback
                          </div>
                          <div className="inline-block px-2 py-1 rounded-full bg-gray-100 text-gray-600 dark:bg-gray-800 dark:text-gray-400 text-xs font-medium">
                            Coaching
                          </div>
                        </div>
                      </TableCell>
                      <TableCell>
                        <div className="flex items-center gap-2">
                          <Button size="sm" variant="outline">
                            <DeleteIcon className="w-4 h-4" />
                            Edit
                          </Button>
                          <Button size="sm" variant="destructive">
                            <TrashIcon className="w-4 h-4" />
                            Delete
                          </Button>
                        </div>
                      </TableCell>
                    </TableRow>
                  </TableBody>
                </Table>
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  )
}

function DeleteIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 5H9l-7 7 7 7h11a2 2 0 0 0 2-2V7a2 2 0 0 0-2-2Z" />
      <line x1="18" x2="12" y1="9" y2="15" />
      <line x1="12" x2="18" y1="9" y2="15" />
    </svg>
  )
}


function TrashIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 6h18" />
      <path d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6" />
      <path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2" />
    </svg>
  )
}

export default Menu;