/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Z9TjZdO9vvN
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "../../components/ui/button";
import {
  DropdownMenuTrigger,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuItem,
  DropdownMenuContent,
  DropdownMenu,
} from "../../components/ui/dropdown-menu";
import { CardContent, Card } from "../../components/ui/card";
import { Textarea } from "../../components/ui/textarea";
import Link from "../../../node_modules/next/link";

const Show = () => {
  return (
    <>
      <div className="flex-column p-6 h-full bg-[#f7f7f7] justify-center content-center overflow-y-scroll">
        <div className="grid gap-4">
          <div className="grid gap-2">
            <div className="flex items-center justify-between">
              <h2 className="text-lg font-semibold">Assignment 1</h2>
            </div>
            <Card>
              <CardContent className="grid gap-4">
                <div className="flex items-center gap-2 mt-6">
                  <img
                    alt="Note thumbnail"
                    className="rounded-md"
                    height="40"
                    src="/placeholder.svg"
                    style={{
                      aspectRatio: "40/40",
                      objectFit: "cover",
                    }}
                    width="40"
                  />
                  <div className="flex-1">
                    <h3 className="text-sm font-medium">Assignment 1</h3>
                    <p className="text-xs text-gray-500 dark:text-gray-400">
                      Created 2 days ago
                    </p>
                  </div>
                </div>
                <div className="grid gap-4">
                  <div>
                    <div className="grid gap-4">
                      <div className="flex flex-col">
                        <p className="text-sm text-gray-500 dark:text-gray-400">
                          Practice Date
                        </p>
                        <DropdownMenu>
                          <DropdownMenuTrigger asChild>
                            <Button
                              className="text-sm font-medium"
                              variant="outline"
                            >
                              April 25, 2023
                              <ChevronDownIcon className="ml-2 h-4 w-4" />
                            </Button>
                          </DropdownMenuTrigger>
                          <DropdownMenuContent align="bottom">
                            <DropdownMenuItem>April 25, 2023</DropdownMenuItem>
                            <DropdownMenuItem>May 2, 2023</DropdownMenuItem>
                            <DropdownMenuItem>May 9, 2023</DropdownMenuItem>
                          </DropdownMenuContent>
                        </DropdownMenu>
                      </div>
                      <div className="flex flex-col">
                        <p className="text-sm text-gray-500 dark:text-gray-400">
                          Practice Place
                        </p>
                        <DropdownMenu>
                          <DropdownMenuTrigger asChild>
                            <Button
                              className="text-sm font-medium"
                              variant="outline"
                            >
                              Acme University Gym
                              <ChevronDownIcon className="ml-2 h-4 w-4" />
                            </Button>
                          </DropdownMenuTrigger>
                          <DropdownMenuContent align="bottom">
                            <DropdownMenuItem>
                              Acme University Gym
                            </DropdownMenuItem>
                            <DropdownMenuItem>
                              Offsite Training Facility
                            </DropdownMenuItem>
                            <DropdownMenuItem>Home Gym</DropdownMenuItem>
                          </DropdownMenuContent>
                        </DropdownMenu>
                      </div>
                      <div className="flex flex-col">
                        <p className="text-sm text-gray-500 dark:text-gray-400">
                          Practice Menu
                        </p>
                        <div className="grid gap-2">
                          <DropdownMenu>
                            <DropdownMenuTrigger asChild>
                              <Button
                                className="text-sm font-medium"
                                variant="outline"
                              >
                                Warm-up, Strength Training, Cardio
                                <ChevronDownIcon className="ml-2 h-4 w-4" />
                              </Button>
                            </DropdownMenuTrigger>
                            <DropdownMenuContent align="bottom">
                              <DropdownMenuItem>
                                Warm-up, Strength Training, Cardio
                              </DropdownMenuItem>
                              <DropdownMenuItem>
                                Yoga, Pilates, Stretching
                              </DropdownMenuItem>
                              <DropdownMenuItem>
                                HIIT, Plyometrics, Agility
                              </DropdownMenuItem>
                            </DropdownMenuContent>
                          </DropdownMenu>
                          <DropdownMenu>
                            <DropdownMenuTrigger asChild>
                              <Button
                                className="text-sm font-medium"
                                variant="outline"
                              >
                                Flexibility, Balance, Mobility
                                <ChevronDownIcon className="ml-2 h-4 w-4" />
                              </Button>
                            </DropdownMenuTrigger>
                            <DropdownMenuContent align="bottom">
                              <DropdownMenuItem>
                                Flexibility, Balance, Mobility
                              </DropdownMenuItem>
                              <DropdownMenuItem>
                                Plyometrics, Speed, Agility
                              </DropdownMenuItem>
                              <DropdownMenuItem>
                                Core, Stability, Posture
                              </DropdownMenuItem>
                            </DropdownMenuContent>
                          </DropdownMenu>
                        </div>
                      </div>
                    </div>
                  </div>
                  <div>
                    <h3 className="text-sm font-medium">Comment</h3>
                    <div className="grid gap-4">
                      <Card>
                        <CardContent className="grid gap-4 mt-6">
                          <p className="text-sm text-gray-500 dark:text-gray-400">
                            Great work on the assignment! I like how you've
                            structured the research proposal. Let's discuss the
                            next steps in our meeting.
                          </p>
                        </CardContent>
                      </Card>
                    </div>
                  </div>
                  <div>
                    <h3 className="text-sm font-medium">Supervisor Feedback</h3>
                    <div className="grid gap-4">
                      <Card>
                        <CardContent className="grid gap-4 mt-6">
                          <div className="flex items-center gap-2">
                            <img
                              alt="Supervisor avatar"
                              className="rounded-full"
                              height="40"
                              src="/placeholder.svg"
                              style={{
                                aspectRatio: "40/40",
                                objectFit: "cover",
                              }}
                              width="40"
                            />
                            <div className="flex-1">
                              <h3 className="text-sm font-medium">Jane Doe</h3>
                              <p className="text-xs text-gray-500 dark:text-gray-400">
                                Supervisor
                              </p>
                            </div>
                            <p className="text-xs text-gray-500 dark:text-gray-400">
                              2 days ago
                            </p>
                          </div>
                          <p className="text-sm text-gray-500 dark:text-gray-400">
                            Great work on the assignment! I like how you've
                            structured the research proposal. Let's discuss the
                            next steps in our meeting.
                          </p>
                        </CardContent>
                      </Card>
                    </div>
                  </div>
                  <div>
                    <h3 className="text-sm font-medium">Chat</h3>
                    <div className="grid gap-4">
                      <Card>
                        <CardContent className="grid gap-4 mt-6">
                          <div className="flex items-start gap-2">
                            <img
                              alt="Student avatar"
                              className="rounded-full"
                              height="40"
                              src="/placeholder.svg"
                              style={{
                                aspectRatio: "40/40",
                                objectFit: "cover",
                              }}
                              width="40"
                            />
                            <div className="flex-1">
                              <div className="flex items-center justify-between">
                                <h3 className="text-sm font-medium">
                                  John Doe
                                </h3>
                                <p className="text-xs text-gray-500 dark:text-gray-400">
                                  2 days ago
                                </p>
                              </div>
                              <p className="text-sm text-gray-500 dark:text-gray-400">
                                Hi Jane, I have a few questions about the
                                assignment. Can we schedule a quick call to
                                discuss?
                              </p>
                            </div>
                          </div>
                          <div className="flex items-start gap-2">
                            <img
                              alt="Supervisor avatar"
                              className="rounded-full"
                              height="40"
                              src="/placeholder.svg"
                              style={{
                                aspectRatio: "40/40",
                                objectFit: "cover",
                              }}
                              width="40"
                            />
                            <div className="flex-1">
                              <div className="flex items-center justify-between">
                                <h3 className="text-sm font-medium">
                                  Jane Doe
                                </h3>
                                <p className="text-xs text-gray-500 dark:text-gray-400">
                                  1 day ago
                                </p>
                              </div>
                              <p className="text-sm text-gray-500 dark:text-gray-400">
                                Sure, John. Let's schedule a 30-minute call
                                tomorrow at 2pm. I'll send you a calendar
                                invite.
                              </p>
                            </div>
                          </div>
                          <div className="flex items-start gap-2">
                            <img
                              alt="Student avatar"
                              className="rounded-full"
                              height="40"
                              src="/placeholder.svg"
                              style={{
                                aspectRatio: "40/40",
                                objectFit: "cover",
                              }}
                              width="40"
                            />
                            <div className="flex-1">
                              <div className="flex items-center justify-between">
                                <h3 className="text-sm font-medium">
                                  John Doe
                                </h3>
                                <p className="text-xs text-gray-500 dark:text-gray-400">
                                  1 day ago
                                </p>
                              </div>
                              <p className="text-sm text-gray-500 dark:text-gray-400">
                                Sounds good, Jane. I'll be there. Thanks!
                              </p>
                            </div>
                          </div>
                          <div className="flex items-start gap-2">
                            <img
                              alt="Supervisor avatar"
                              className="rounded-full"
                              height="40"
                              src="/placeholder.svg"
                              style={{
                                aspectRatio: "40/40",
                                objectFit: "cover",
                              }}
                              width="40"
                            />
                            <div className="flex-1">
                              <div className="flex items-center justify-between">
                                <h3 className="text-sm font-medium">
                                  Jane Doe
                                </h3>
                                <p className="text-xs text-gray-500 dark:text-gray-400">
                                  1 day ago
                                </p>
                              </div>
                              <p className="text-sm text-gray-500 dark:text-gray-400">
                                Great, I'm looking forward to our call. Let me
                                know if you have any other questions in the
                                meantime.
                              </p>
                            </div>
                          </div>
                          <div className="flex items-center gap-2">
                            <img
                              alt="Student avatar"
                              className="rounded-full"
                              height="40"
                              src="/placeholder.svg"
                              style={{
                                aspectRatio: "40/40",
                                objectFit: "cover",
                              }}
                              width="40"
                            />
                            <Textarea
                              className="flex-1 rounded-md border border-gray-200 p-2 text-sm dark:border-gray-800 dark:bg-gray-900 dark:text-gray-50 dark:border-gray-800"
                              placeholder="Enter your comment..."
                            />
                          </div>
                        </CardContent>
                      </Card>
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>
          </div>
        </div>
      </div>
    </>
  );
}

function ChevronDownIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m6 9 6 6 6-6" />
    </svg>
  );
}

export default  Show;