/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/6VfAavfVBtV
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

import { useEffect } from "react";
import { useRouter } from "../../../node_modules/next/router";

const CompletionUserRegisteration = () => {
  const router = useRouter();

  useEffect(() => {
    // リダイレクト処理を行う
    const redirectToCompletion = async () => {
      try {
        // 遷移先URLにリダイレクト
        await router.push('/auth/completion-user-registration');
      } catch (error) {
        console.error('リダイレクト中にエラーが発生しました:', error);
      }
    };
  
    // コンポーネントがマウントされた後にリダイレクト処理を実行
    redirectToCompletion();
  }, []); // 空の依存配列を渡して、マウント時の1回のみ実行するように設定

  return (
    <div className="flex h-screen bg-[#f7f7f7] justify-center items-center">
      <div className="bg-white p-8 rounded-lg shadow-lg max-w-sm w-full text-center">
        <div className="mb-6">
          <svg
            aria-hidden="true"
            className="mx-auto h-12 w-12 text-green-600"
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
          >
            <path d="M5 13l4 4L19 7" strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} />
          </svg>
        </div>
        <h1 className="text-2xl font-bold mb-2">登録完了</h1>
        <p className="text-gray-500 mb-6">ご登録ありがとうございます。ログインページからお進みください。</p>
        <a
          className="inline-flex items-center px-4 py-2 border border-gray-200 border-transparent text-sm font-medium rounded-md text-white bg-blue-600 hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-blue-500 dark:border-gray-800"
          href="./login"
        >
          ログインページへ
        </a>
      </div>
    </div>
  )
}

export default CompletionUserRegisteration;