/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/9NulHEwCECM
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

import Link from "../../../node_modules/next/link";
import React, { FormEvent, useState } from "react";
import { useRouter } from "../../../node_modules/next/router";
import apiClient from "@/lib/apiClient";

const Login = () => {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const router = useRouter();

  const handleSubmit = async (e: FormEvent) => {
    e.preventDefault();

    try {
      apiClient.post("/auth/login", {
        email,
        password,
      });
      router.push("/auth/mypage");
    } catch (error) {
      console.error("Error", error);
    }
  };

  return (
    <div className="flex h-screen bg-[#f7f7f7] justify-center items-center">
      <div className="bg-white p-8 rounded-lg shadow-lg max-w-sm w-full m-4">
        <h1 className="text-2xl font-bold mb-6">ログイン</h1>
        <form className="space-y-4" onSubmit={handleSubmit}>
          <div>
            <label className="sr-only" htmlFor="email">
              メールアドレス
            </label>
            <input
              className="w-full px-3 py-2 border border-gray-200 rounded-md dark:border-gray-800"
              id="email"
              placeholder="メールアドレス"
              required
              type="email"
              name="email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
            />
          </div>
          <div>
            <label className="sr-only" htmlFor="password">
              パスワード
            </label>
            <input
              className="w-full px-3 py-2 border border-gray-200 rounded-md dark:border-gray-800"
              id="password"
              placeholder="パスワード"
              required
              type="password"
              name="password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
            />
          </div>
          <div className="flex items-center justify-between">
            <button
              className="w-full px-3 py-2 bg-blue-600 text-white rounded-md"
              type="submit"
            >
              ログイン
            </button>
          </div>
          <div className="flex items-center justify-between">
            <Link
              className="text-blue-600 hover:underline ml-4"
              href="./email-verification"
            >
              パスワードをお忘れですか？
            </Link>
          </div>
        </form>
      </div>
    </div>
  );
};

export default Login;
