/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/gM7DgCLNrdi
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "../../components/ui/button";
import { Input } from "../../components/ui/input";
import { CardContent, Card } from "../../components/ui/card";
import {
  PaginationPrevious,
  PaginationItem,
  PaginationLink,
  PaginationEllipsis,
  PaginationNext,
  PaginationContent,
  Pagination,
} from "../../components/ui/pagination";

const Index = () => {
  return (
    <>
      <main className="flex-1 overflow-auto p-4">
        <div className="grid gap-4">
          <div className="grid gap-2">
            <div className="flex items-center justify-between">
              <h2 className="text-lg font-semibold">練習記録</h2>
            </div>
            <div className="flex items-center justify-end gap-10 mt-4">
              <div className="relative">
                <Input
                  className="pr-8 rounded-md border border-gray-200 bg-gray-100 py-2 px-4 text-lg focus:border-gray-300 focus:outline-none dark:border-gray-800 dark:bg-gray-800 dark:text-gray-200 dark:border-gray-800"
                  placeholder="キーワードを入力"
                  type="text"
                />
                <SearchIcon className="absolute right-2 top-1/2 h-5 w-5 -translate-y-1/2 text-gray-500 dark:text-gray-400" />
              </div>
              <Button size="sm">新規作成</Button>
            </div>
            <div className="grid gap-6 mt-6">
              <Card>
                <CardContent className="grid gap-2 p-6">
                  <div className="flex items-center gap-2">
                    <img
                      alt="Note thumbnail"
                      className="rounded-md"
                      height="40"
                      src="/placeholder.svg"
                      style={{
                        aspectRatio: "40/40",
                        objectFit: "cover",
                      }}
                      width="40"
                    />
                    <div className="flex-1">
                      <h3 className="text-sm font-medium">Assignment 1</h3>
                      <p className="text-xs text-gray-500 dark:text-gray-400">
                        Created 2 days ago
                      </p>
                    </div>
                    <Button size="icon" variant="ghost">
                      <MoreVerticalIcon className="h-5 w-5 text-gray-500 dark:text-gray-400" />
                    </Button>
                  </div>
                  <p className="text-sm text-gray-500 dark:text-gray-400 line-clamp-2">
                    This is the first assignment for the semester, covering the
                    basics of note-taking and research methods.
                  </p>
                </CardContent>
              </Card>
              <Card>
                <CardContent className="grid gap-2 p-6">
                  <div className="flex items-center gap-2">
                    <img
                      alt="Note thumbnail"
                      className="rounded-md"
                      height="40"
                      src="/placeholder.svg"
                      style={{
                        aspectRatio: "40/40",
                        objectFit: "cover",
                      }}
                      width="40"
                    />
                    <div className="flex-1">
                      <h3 className="text-sm font-medium">Lab Report</h3>
                      <p className="text-xs text-gray-500 dark:text-gray-400">
                        Created 5 days ago
                      </p>
                    </div>
                    <Button size="icon" variant="ghost">
                      <MoreVerticalIcon className="h-5 w-5 text-gray-500 dark:text-gray-400" />
                    </Button>
                  </div>
                  <p className="text-sm text-gray-500 dark:text-gray-400 line-clamp-2">
                    This is the lab report for the chemistry experiment we
                    conducted last week.
                  </p>
                </CardContent>
              </Card>
              <Card>
                <CardContent className="grid gap-2 p-6">
                  <div className="flex items-center gap-2">
                    <img
                      alt="Note thumbnail"
                      className="rounded-md"
                      height="40"
                      src="/placeholder.svg"
                      style={{
                        aspectRatio: "40/40",
                        objectFit: "cover",
                      }}
                      width="40"
                    />
                    <div className="flex-1">
                      <h3 className="text-sm font-medium">Research Proposal</h3>
                      <p className="text-xs text-gray-500 dark:text-gray-400">
                        Created 10 days ago
                      </p>
                    </div>
                    <Button size="icon" variant="ghost">
                      <MoreVerticalIcon className="h-5 w-5 text-gray-500 dark:text-gray-400" />
                    </Button>
                  </div>
                  <p className="text-sm text-gray-500 dark:text-gray-400 line-clamp-2">
                    This is the research proposal for my final project,
                    outlining the topic, methodology, and expected outcomes.
                  </p>
                </CardContent>
              </Card>
              {/* <Card>
                <CardContent className="grid gap-2 p-6">
                  <div className="flex items-center gap-2">
                    <img
                      alt="Note thumbnail"
                      className="rounded-md"
                      height="40"
                      src="/placeholder.svg"
                      style={{
                        aspectRatio: "40/40",
                        objectFit: "cover",
                      }}
                      width="40"
                    />
                    <div className="flex-1">
                      <h3 className="text-sm font-medium">Research Proposal</h3>
                      <p className="text-xs text-gray-500 dark:text-gray-400">Created 10 days ago</p>
                    </div>
                    <Button size="icon" variant="ghost">
                      <MoreVerticalIcon className="h-5 w-5 text-gray-500 dark:text-gray-400" />
                    </Button>
                  </div>
                  <p className="text-sm text-gray-500 dark:text-gray-400 line-clamp-2">
                    This is the research proposal for my final project, outlining the topic, methodology, and expected
                    outcomes.
                  </p>
                </CardContent>
              </Card> */}
            </div>
          </div>
        </div>
        <div className="flex justify-center mt-8">
          <Pagination>
            <PaginationContent>
              <PaginationItem>
                <PaginationPrevious href="#" />
              </PaginationItem>
              <PaginationItem>
                <PaginationLink href="#">1</PaginationLink>
              </PaginationItem>
              <PaginationItem>
                <PaginationLink href="#" isActive>
                  2
                </PaginationLink>
              </PaginationItem>
              <PaginationItem>
                <PaginationLink href="#">3</PaginationLink>
              </PaginationItem>
              <PaginationItem>
                <PaginationEllipsis />
              </PaginationItem>
              <PaginationItem>
                <PaginationNext href="#" />
              </PaginationItem>
            </PaginationContent>
          </Pagination>
        </div>
      </main>
    </>
  );
};

// function FilterIcon(props) {
//   return (
//     <svg
//       {...props}
//       xmlns="http://www.w3.org/2000/svg"
//       width="24"
//       height="24"
//       viewBox="0 0 24 24"
//       fill="none"
//       stroke="currentColor"
//       strokeWidth="2"
//       strokeLinecap="round"
//       strokeLinejoin="round"
//     >
//       <polygon points="22 3 2 3 10 12.46 10 19 14 21 14 12.46 22 3" />
//     </svg>
//   )
// }

function MenuIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>
  );
}

function MoreVerticalIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="1" />
      <circle cx="12" cy="5" r="1" />
      <circle cx="12" cy="19" r="1" />
    </svg>
  );
}

// function PlusIcon(props) {
//   return (
//     <svg
//       {...props}
//       xmlns="http://www.w3.org/2000/svg"
//       width="24"
//       height="24"
//       viewBox="0 0 24 24"
//       fill="none"
//       stroke="currentColor"
//       strokeWidth="2"
//       strokeLinecap="round"
//       strokeLinejoin="round"
//     >
//       <path d="M5 12h14" />
//       <path d="M12 5v14" />
//     </svg>
//   )
// }

function SearchIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  );
}


export default Index;