/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/dxwFbZ34k0b
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/

import { Button } from "@/components/ui/button";
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar";
import Link from "../../node_modules/next/link";

export function Mypage() {
  return (
    <>
      <main className="flex-1 overflow-auto p-4">
        <div className="col-span-2 rounded-lg border border-gray-200 bg-white p-6 m-4 shadow-sm dark:border-gray-800 dark:bg-gray-900 dark:border-gray-800">
          <div className="flex items-center justify-between">
            <h2 className="text-lg font-semibold">User Information</h2>
          </div>
          <div className="mt-4 grid gap-4">
            <div className="rounded-lg border border-gray-200 bg-gray-100 p-4 dark:border-gray-800 dark:bg-gray-950 dark:border-gray-800">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <Avatar>
                    <AvatarImage alt="John Doe" />
                    <AvatarFallback>JD</AvatarFallback>
                  </Avatar>
                  <div>
                    <div className="font-medium">John Doe</div>
                    <div className="text-sm text-gray-500 dark:text-gray-400">
                      Coach, Acme FC
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div className="container grid grid-cols-1 md:grid-cols-2">
          <div className="rounded-lg border border-gray-200 bg-white p-6 m-4 shadow-sm dark:border-gray-800 dark:bg-gray-900 dark:border-gray-800">
            <div className="flex items-center justify-between">
              <h2 className="text-lg font-semibold">連携中ユーザー</h2>
            </div>
            <div className="mt-4 grid gap-4">
              <div className="rounded-lg border border-gray-200 bg-gray-100 p-4 dark:border-gray-800 dark:bg-gray-950 dark:border-gray-800">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <Avatar>
                      <AvatarImage alt="Jane Smith" />
                      <AvatarFallback>JS</AvatarFallback>
                    </Avatar>
                    <div>
                      <div className="font-medium">Jane Smith</div>
                      <div className="text-sm text-gray-500 dark:text-gray-400">
                        Coach, Acme FC
                      </div>
                    </div>
                  </div>
                  <div className="flex items-center gap-2">
                    {/* <Button size="sm" variant="ghost">
                      <LinkIcon className="h-4 w-4" />
                      <span>Linked</span>
                    </Button> */}
                    <Button
                      className="text-red-500 hover:bg-red-100 dark:hover:bg-red-900"
                      size="sm"
                      variant="ghost"
                    >
                      <TrashIcon className="h-4 w-4" />
                      <span>Delete</span>
                    </Button>
                  </div>
                </div>
              </div>
              <div className="rounded-lg border border-gray-200 bg-gray-100 p-4 dark:border-gray-800 dark:bg-gray-950 dark:border-gray-800">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <Avatar>
                      <AvatarImage alt="John Doe" />
                      <AvatarFallback>JD</AvatarFallback>
                    </Avatar>
                    <div>
                      <div className="font-medium">John Doe</div>
                      <div className="text-sm text-gray-500 dark:text-gray-400">
                        Player, Acme FC
                      </div>
                    </div>
                  </div>
                  <div className="flex items-center gap-2">
                    {/* <Button size="sm" variant="ghost">
                      <LinkIcon className="h-4 w-4" />
                      <span>Linked</span>
                    </Button> */}
                    <Button
                      className="text-red-500 hover:bg-red-100 dark:hover:bg-red-900"
                      size="sm"
                      variant="ghost"
                    >
                      <TrashIcon className="h-4 w-4" />
                      <span>Delete</span>
                    </Button>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="col-span-2 rounded-lg border border-gray-200 bg-white p-6 m-4 shadow-sm dark:border-gray-800 dark:bg-gray-900 dark:border-gray-800">
            <div className="flex items-center justify-between">
              <h2 className="text-lg font-semibold">ユーザー連携</h2>
              <Button size="sm">QRスキャン</Button>
            </div>
            <div className="mt-4 grid gap-4">
              <div className="rounded-lg border border-gray-200 bg-gray-100 p-4 dark:border-gray-800 dark:bg-gray-950 dark:border-gray-800">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <div className="w-16 h-16 bg-gray-200 rounded-lg flex items-center justify-center dark:bg-gray-800">
                      <QrCodeIcon className="h-8 w-8 text-gray-500 dark:text-gray-400" />
                    </div>
                    <div>
                      <div className="font-medium">Scan QR Code</div>
                      <div className="text-sm text-gray-500 dark:text-gray-400">
                        Scan the QR code to link with a coach or player.
                      </div>
                    </div>
                  </div>          
                </div>
              </div>
              <div className="rounded-lg border border-gray-200 bg-gray-100 p-4 dark:border-gray-800 dark:bg-gray-950 dark:border-gray-800">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <div className="w-16 h-16 bg-gray-200 rounded-lg flex items-center justify-center dark:bg-gray-800">
                      <KeyIcon className="h-8 w-8 text-gray-500 dark:text-gray-400" />
                    </div>
                    <div>
                      <div className="font-medium">Reset Password</div>
                      <div className="text-sm text-gray-500 dark:text-gray-400">
                        Navigate to the password reset page.
                      </div>
                    </div>
                  </div>
                  <div className="flex items-center gap-2">
                    <Button size="sm">再設定</Button>
                  </div>
                </div>
              </div>
              <div className="rounded-lg border border-gray-200 bg-gray-100 p-4 dark:border-gray-800 dark:bg-gray-950 dark:border-gray-800">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <div className="w-16 h-16 bg-gray-200 rounded-lg flex items-center justify-center dark:bg-gray-800">
                      <TrashIcon className="h-8 w-8 text-gray-500 dark:text-gray-400" />
                    </div>
                    <div>
                      <div className="font-medium">Delete User</div>
                      <div className="text-sm text-gray-500 dark:text-gray-400">
                        Remove a user from the system.
                      </div>
                    </div>
                  </div>
                  <div className="flex items-center gap-2">
                    <Button
                      className="text-red-500 hover:bg-red-100 dark:hover:bg-red-900"
                      size="sm"
                      variant="ghost"
                    >
                      <TrashIcon className="h-4 w-4" />
                      <span>削除</span>
                    </Button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}

function KeyIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="7.5" cy="15.5" r="5.5" />
      <path d="m21 2-9.6 9.6" />
      <path d="m15.5 7.5 3 3L22 7l-3-3" />
    </svg>
  );
}

function LinkIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M10 13a5 5 0 0 0 7.54.54l3-3a5 5 0 0 0-7.07-7.07l-1.72 1.71" />
      <path d="M14 11a5 5 0 0 0-7.54-.54l-3 3a5 5 0 0 0 7.07 7.07l1.71-1.71" />
    </svg>
  );
}

function QrCodeIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="5" height="5" x="3" y="3" rx="1" />
      <rect width="5" height="5" x="16" y="3" rx="1" />
      <rect width="5" height="5" x="3" y="16" rx="1" />
      <path d="M21 16h-3a2 2 0 0 0-2 2v3" />
      <path d="M21 21v.01" />
      <path d="M12 7v3a2 2 0 0 1-2 2H7" />
      <path d="M3 12h.01" />
      <path d="M12 3h.01" />
      <path d="M12 16v.01" />
      <path d="M16 12h1" />
      <path d="M21 12v.01" />
      <path d="M12 21v-1" />
    </svg>
  );
}

function TrashIcon(props:any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M3 6h18" />
      <path d="M19 6v14c0 1-1 2-2 2H7c-1 0-2-1-2-2V6" />
      <path d="M8 6V4c0-1 1-2 2-2h4c1 0 2 1 2 2v2" />
    </svg>
  );
}
